name: lambda
on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/lambda.yml
      - v2/**

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  deploy:
    defaults:
    run:
      working-directory: "./v2"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: go build
      run: GOOS=linux CGO_ENABLED=0 go build main.go

    - name: create zip
      run: zip function.zip main

    - name: publish lambda
      run: |
        aws lambda update-function-code --function-name WW3Api --zip-file fileb://function.zip

    - name: increment lambda version
      run: aws lambda publish-version --function-name WW3Api
